#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
import os.path
from cmp.gui import CMPGUI

if __name__ == "__main__":

    cmpgui = CMPGUI()
    if len(sys.argv) >= 2 and os.path.isfile(sys.argv[1]):
        cmpgui.load_state(sys.argv[1])

    cmpgui.show()
